更新ubuntu workflow支持runner
Signed-off-by: yifengyou <842056007@qq.com>

diff --git a/.github/workflows/qcow2-ubuntu.yml b/.github/workflows/qcow2-ubuntu.yml
--- a/.github/workflows/qcow2-ubuntu.yml
+++ b/.github/workflows/qcow2-ubuntu.yml
@@ -12,6 +12,7 @@ on:
         options:
           - amd64
           - arm64
+          - arm64-runner
 
 env:
   TZ: America/New_York
@@ -245,6 +246,134 @@ jobs:
             - **安全提示**：请及时修改默认密码，配置防火墙，请谨慎开放端口
 
 
+  build-arm64-runner:
+    if: ${{ github.event.inputs.arch_type == 'arm64-runner' }}
+    runs-on: ubuntu-22.04
+    timeout-minutes: 60
+    strategy:
+      matrix:
+        os_release: [
+            'ubuntu-24.04.4-live-server-arm64.iso',
+            'ubuntu-24.04.3-live-server-arm64.iso',
+            'ubuntu-24.04.2-live-server-arm64.iso',
+            'ubuntu-24.04.1-live-server-arm64.iso',
+            'ubuntu-24.04-live-server-arm64.iso',
+            'ubuntu-22.04.5-live-server-arm64.iso',
+            'ubuntu-22.04.4-live-server-arm64.iso',
+            'ubuntu-22.04.3-live-server-arm64.iso',
+            'ubuntu-22.04.2-live-server-arm64.iso',
+            'ubuntu-22.04.1-live-server-arm64.iso',
+            'ubuntu-22.04-live-server-arm64.iso',
+            'ubuntu-20.04.5-live-server-arm64.iso',
+            'ubuntu-20.04.4-live-server-arm64.iso',
+            'ubuntu-20.04.3-live-server-arm64.iso',
+            'ubuntu-20.04.2-live-server-arm64.iso',
+            'ubuntu-20.04.1-live-server-arm64.iso',
+            'ubuntu-20.04-live-server-arm64.iso',
+        ]
+      max-parallel: 8
+      fail-fast: false
+    steps:
+      - name: Check repo
+        working-directory: /kdev/
+        run: |
+          set -x
+          if [ -d kdev.git ]; then
+            cd kdev.git
+            ls -alh
+          else
+            sudo git clone https://github.com/yifengyou/kdev.git
+            sudo chown -R builder:builder kdev.git
+            git config --global --add safe.directory /kdev/kdev.git
+            cd kdev.git
+            ls -alh
+          fi
 
+      - name: Install dependency
+        run: |
+          set -x
+          lscpu
+          ls -alh /dev/kvm || :
+          sudo mkdir -p /builder/release
+
+      - name: Build rootfs in vm
+        timeout-minutes: 120
+        working-directory: /kdev/kdev.git/
+        run: |
+          set -x
+          ls -alh
+          cd iso/${{ matrix.os_release }}
+          sudo ./build-vm.sh
+
+      - name: Compress qcow2 image
+        timeout-minutes: 20
+        working-directory: /builder/
+        run: |
+          set -x
+          cd iso/${{ matrix.os_release }}
+          ls -alh
+          mkdir -p /kdev/kdev.git/release
+
+          FILE_PATH="/kdev/kdev.git/release/kdev_${{ matrix.os_release }}.qcow2.tar.gz"
+          FILE_NAME=$(basename ${FILE_PATH})
+
+          if [ -f ${FILE_PATH} ]; then
+            # check upload
+            REMOTE_HASH=$(curl -s -H "Accept: application/vnd.github+json" "https://api.github.com/repos/yifengyou/kdev/releases/tags/debian-qcow2" | jq -r --arg n "${FILE_NAME}" '.assets[] | select(.name == $n) | .digest' | cut -d: -f2)
+            LOCAL_HASH=$(sha256sum ${FILE_PATH} | awk '{print $1}')
+            if [[ "$REMOTE_HASH" == "$LOCAL_HASH" ]]; then
+              echo "已存在相同文件，忽略上传流程"
+              echo "SKIP_UPLOAD=true" >> $GITHUB_ENV
+            fi
+            exit 0
+          fi
+
+          sudo tar -zcvf /kdev/kdev.git/release/kdev_${{ matrix.os_release }}.qcow2.tar.gz rootfs.qcow2
+          ls -alh /kdev/kdev.git/release
+
+          # check file size
+          FILE_SIZE=$(stat -c%s "$FILE_PATH")
+          LIMIT_SIZE=$((80 * 1024 * 1024))
+          echo "文件大小: $FILE_SIZE 字节"
+          echo "限制大小: $LIMIT_SIZE 字节"
+          if [ "$FILE_SIZE" -lt "$LIMIT_SIZE" ]; then
+            echo "::error::❌ 打包失败：文件 $FILE_NAME 大小为 $(($FILE_SIZE / 1024 / 1024))M，小于 80M 的最低要求！"
+            exit 1
+          else
+            echo "✅ 检查通过：文件大小符合要求。"
+          fi
+
+          # check upload
+          REMOTE_HASH=$(curl -s -H "Accept: application/vnd.github+json" "https://api.github.com/repos/yifengyou/kdev/releases/tags/debian-qcow2" | jq -r --arg n "${FILE_NAME}" '.assets[] | select(.name == $n) | .digest' | cut -d: -f2)
+          LOCAL_HASH=$(sha256sum ${FILE_PATH} | awk '{print $1}')
+          if [[ "$REMOTE_HASH" == "$LOCAL_HASH" ]]; then
+            echo "✅ 已存在相同文件，忽略上传流程"
+            echo "SKIP_UPLOAD=true" >> $GITHUB_ENV
+          fi
+
+      - name: Upload image to release
+        uses: ncipollo/release-action@main
+        timeout-minutes: 60
+        with:
+          tag: ubuntu-qcow2
+          artifacts: /kdev/kdev.git/release/kdev_${{ matrix.os_release }}.qcow2.tar.gz
+          allowUpdates: true
+          removeArtifacts: false
+          replacesArtifacts: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+          body: | # ubuntu qcow2
+
+            ## 镜像信息
+
+            1. ISO来源于 Ubuntu 官方 <https://releases.ubuntu.com/>
+            2. 支持架构：amd64 / arm64
+            3. root账号密码: root 密码 linux
+            4. 普通用户账号密码： kdev 密码 linux
+
+            ## 免责声明
+
+            - **按原样提供**：本镜像不作任何明示或暗示保证，使用风险由用户自行承担
+            - **无官方关联**：Ubuntu 是开源社区项目，本镜像与 Ubuntu 团队无官方关联
+            - **安全提示**：请及时修改默认密码，配置防火墙，请谨慎开放端口
 
 
