add workflow runner
Signed-off-by: yifengyou <842056007@qq.com>

diff --git a/.github/workflows/qcow2-debian.yml b/.github/workflows/qcow2-debian.yml
--- a/.github/workflows/qcow2-debian.yml
+++ b/.github/workflows/qcow2-debian.yml
@@ -12,6 +12,7 @@ on:
         options:
           - amd64
           - arm64
+          - arm64-runner
 
 env:
   TZ: America/New_York
@@ -271,5 +272,89 @@ jobs:
             - **按原样提供**：本镜像不作任何明示或暗示保证，使用风险由用户自行承担
             - **无官方关联**：debian 是开源社区项目，本镜像与 debian 团队无官方关联
             - **安全提示**：请及时修改默认密码，配置防火墙，请谨慎开放端口
+
+  build-arm64-runner:
+    if: ${{ github.event.inputs.arch_type == 'arm64-runner' }}
+    runs-on: ubuntu-24.04-arm
+    strategy:
+      matrix:
+        os_release: [
+            'debian-13.4.0-arm64-DVD-1.iso',
+            'debian-13.3.0-arm64-DVD-1.iso',
+        ]
+      max-parallel: 64
+      fail-fast: false
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v5
+
+      - name: Install dependency
+        run: |
+          set -x
+          uname -a
+          lscpu
+          ls -alh /dev/kvm || :
+          sudo apt update
+          sudo apt install -qq -y qemu-kvm libvirt-daemon-system virtinst cpu-checker aria2
+          sudo systemctl enable --now libvirtd
+          sudo mkdir -p /builder/release
+
+      - name: Build rootfs in vm
+        timeout-minutes: 120
+        working-directory: /builder/
+        run: |
+          set -x
+          sudo /bin/cp -a ${{ github.workspace }}/* .
+          ls -alh
+          cd iso/${{ matrix.os_release }}
+          sudo ./build-vm.sh
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Compress Rootfs image
+        working-directory: /builder/
+        run: |
+          set -x
+          cd iso/${{ matrix.os_release }}
+          ls -alh
+          sudo tar -zcvf /builder/release/kdev_${{ matrix.os_release }}.qcow2.tar.gz rootfs.qcow2
+          ls -alh /builder/release/
+          FILE_PATH="/builder/release/kdev_${{ matrix.os_release }}.qcow2.tar.gz"
+          FILE_SIZE=$(stat -c%s "$FILE_PATH")
+          LIMIT_SIZE=$((80 * 1024 * 1024))
+          echo "文件大小: $FILE_SIZE 字节"
+          echo "限制大小: $LIMIT_SIZE 字节"
+          if [ "$FILE_SIZE" -lt "$LIMIT_SIZE" ]; then
+            echo "::error::❌ 打包失败：文件 $FILE_NAME 大小为 $(($FILE_SIZE / 1024 / 1024))M，小于 80M 的最低要求！"
+            exit 1
+          else
+            echo "✅ 检查通过：文件大小符合要求。"
+          fi
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Upload image to release
+        uses: ncipollo/release-action@main
+        timeout-minutes: 10
+        with:
+          tag: debian-qcow2
+          artifacts: /builder/release/*
+          allowUpdates: true
+          removeArtifacts: false
+          replacesArtifacts: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+          body: | # debian qcow2
+
+            ## 镜像信息
+
+            1. ISO来源于debian官方 <https://cdimage.debian.org/cdimage/archive/>
+            2. 支持架构：amd64 / arm64
+            3. root账号密码: root 密码 linux
+            4. 普通用户账号密码： kdev 密码 linux
+
+            ## 免责声明
+
+            - **按原样提供**：本镜像不作任何明示或暗示保证，使用风险由用户自行承担
+            - **无官方关联**：debian 是开源社区项目，本镜像与 debian 团队无官方关联
+            - **安全提示**：请及时修改默认密码，配置防火墙，请谨慎开放端口
+
 
 
